feat: Add base for services
approvers/pulsate pull request #22
Opened 2023-09-25 03:01 UTC by MikuroXina

- Move hello as a service
- Add staging terraform
- Add staging workflows

2023-09-25 03:08 UTC, KisaragiEffective requested changes

2023-09-25 03:08 UTC, KisaragiEffective commented on .github/actions/list_dockerfile/action.yml
> +      run: echo "::set-output name=matrix::$(ls services/**/Dockerfile | jq -R -s -c 'split("\n")[:-1]')"
::set-outputは[非推奨](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)です

2023-09-25 03:10 UTC, MikuroXina commented on .github/actions/list_dockerfile/action.yml
> +      run: echo "::set-output name=matrix::$(ls services/**/Dockerfile | jq -R -s -c 'split("\n")[:-1]')"
dad1158 で対応しました

2023-09-25 15:58 UTC, m1sk9 requested changes
Terraform の設定ファイルは `cloudflare_records` でしか触ったことがないのでわかりません. 詳しい人にレビューを託します.

2023-09-25 15:58 UTC, m1sk9 commented on .github/workflows/staging-apply.yaml
> +  TF_CLOUD_ORGANIZATION: "Colk-tech"
これずっと `Colk-tech` に依存してしまうのは避けたいというお気持ち. (どっかそういう話ありましたっけ)

2023-09-25 15:59 UTC, MikuroXina commented on .github/workflows/staging-apply.yaml
> +  TF_CLOUD_ORGANIZATION: "Colk-tech"
別にずっと依存するという訳ではないです. 変えたいときに変えればそれでよいので

2023-09-25 16:03 UTC, m1sk9 commented on .github/workflows/staging-apply.yaml
> +  TF_CLOUD_ORGANIZATION: "Colk-tech"
ok

2023-09-25 16:03 UTC, m1sk9 approved these changes

2023-09-26 04:34 UTC, KisaragiEffective submitted a review, later dismissed

2023-09-26 04:34 UTC, KisaragiEffective commented on .github/actions/list_dockerfile/action.yml
> +      run: echo "matrix=$(ls services/**/Dockerfile | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
現時点でリスクが露見する可能性は小さいものの、マルチバイト文字や改行が入っていると意図した振る舞いをしない可能性があり。
特に改行はパイプで区切り文字として扱われるので悪意を持った入力を将来食うと思わぬ副作用を生む可能性がある。
対策としてはfind -print0で出力すること。

2023-09-26 08:45 UTC, MikuroXina commented on .github/actions/list_dockerfile/action.yml
> +      run: echo "matrix=$(ls services/**/Dockerfile | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
サービス名にマルチバイト文字が混在していても振る舞いに問題はなさそうですが, 改行文字についてはたしかに挙動がおかしくなります. フォルダ名での攻撃もありうるので, 0f90f08 で修正しておきました.

2023-09-26 15:30 UTC, Colk-tech submitted a review, later dismissed

2023-09-26 15:30 UTC, Colk-tech commented on .github/workflows/hadolint.yaml
> +  lint:
```suggestion
      matrix: ${{ steps.set_matrix.outputs.matrix }}

  lint:
```
ごめん シンプルに気になる

2023-09-26 16:24 UTC, laminne approved these changes
LGTM

2023-09-27 05:11 UTC, merged