chore: Feature requestのテンプレートを追加
approvers/pulsate pull request #43
Opened 2023-10-12 06:22 UTC by aqyuki

## 概要
Feature requestのテンプレートを追加

## Note
Issueテンプレートを選択するための設定は別のPRで対応予定

2023-10-12 16:54 UTC, m1sk9 commented
> Issueテンプレートを選択するための設定は別のPRで対応予定
@aqyuki ファイル設置だけでもう有効です.

2023-10-12 19:47 UTC, aqyuki commented
OKです

2023-10-13 12:39 UTC, m1sk9 requested changes
`request.yml` というファイル名は不適切です. どのようなリクエストを受け付けるテンプレートなのかを明確化するために `feature_request.yml` などに rename してください.

2023-10-13 12:39 UTC, m1sk9 commented on .github/ISSUE_TEMPLATE/request.yml
> +body:
```suggestion

body:
```

`bug_report.yml` と相違があるのが気になる.

2023-10-13 12:39 UTC, m1sk9 commented on .github/ISSUE_TEMPLATE/request.yml
> +          required: true
`bug_report.yml` はここが `body` プロパティの最上部なのに, ここでは最下部にしているようですがなにか理由があるんですか?

2023-10-14 00:31 UTC, m1sk9 approved these changes

2023-10-14 00:31 UTC, merged