feat: add SQL migration script
approvers/pulsate pull request #51
Opened 2023-10-29 14:20 UTC by laminne

## What does this PR do?
related: PUL-65 DBスキーマ設計

I have added a migration script for the database.  
We have confirmed that it works with the latest version of Mariadb.  
The migration tool is https://github.com/pressly/goose. We will add documentation on how to develop using this tool in a separate PR soon.

## Additional information
nothing

2023-10-29 14:23 UTC, m1sk9 requested changes

2023-10-29 14:23 UTC, m1sk9 commented on resources/db/20231029225914_init.sql
> +DROP TABLE IF EXISTS note_attachment;
ファイルの最後は改行を入れてください.

2023-10-29 14:25 UTC, laminne commented on resources/db/20231029225914_init.sql
> +DROP TABLE IF EXISTS note_attachment;
fixed at [d99cffe](https://github.com/approvers/pulsate/pull/51/commits/d99cffe13436b2d42c5fda672614d662586f04bf)

2023-10-29 14:27 UTC, m1sk9 submitted a review, later dismissed

2023-10-29 14:27 UTC, laminne commented
[q] Should there be a Dockerfile of the database environment for developers?

2023-10-29 15:01 UTC, MikuroXina requested changes

2023-10-30 01:06 UTC, laminne commented on resources/db/20231029225914_init.sql
> +	bio TEXT DEFAULT '',
他インスタンス(以降リモート)のアカウントは自インスタンス(以降ローカル)にログインすることはないのでログインに必要なメールアドレス/パスワードはNullにするようにしています(よって、この2つにはNOT NULL制約は必要ないと考えます  
bioは確かにNOT NULL制約を追加するべきだと思うので修正します

2023-10-30 06:40 UTC, laminne commented on resources/db/20231029225914_init.sql
> +	text TEXT,
noteのtextが存在しないケースが存在する(画像のみを投稿した場合のtextはNULLになります)のでこれで良いと考えています

2023-10-30 06:45 UTC, laminne commented on resources/db/20231029225914_init.sql
> +	text TEXT,
ただ、NULLよりも空文字列の方が後々扱いやすい可能性はあるので検討する価値はあると思います

2023-10-30 09:23 UTC, MikuroXina approved these changes

2023-10-30 09:33 UTC, merged