feat: Account domain model
approvers/pulsate pull request #60
Opened 2023-11-01 14:04 UTC by laminne

## What does this PR do?

## Additional information

2023-11-06 09:01 UTC, m1sk9 requested changes
気になったところあったのでそこだけ

2023-11-06 09:01 UTC, m1sk9 commented on pkg/accounts/model/account.ts
> +  }
`setFreeze`, `setUnfreeze`, `setSilence` などの命名のほうが直感的でいいと思うんですが, どうですか? ( この `freeze`, `unfreeze`, `silence` はステータスを変更するメソッドですよね? )

2023-11-06 09:11 UTC, laminne commented on pkg/accounts/model/account.ts
> +  }
> この freeze, unfreeze, silence はステータスを変更するメソッドですよね?
そうです。  
setter ではないのでそういう命名にしましたが、setAAA みたいな命名にしたほうがわかりやすいかもしれませんね

2023-11-06 09:12 UTC, laminne commented on deno.json
> -    "include": ["services/hello/"],
初期に作ったものなので多分消していいはず

2023-11-06 09:23 UTC, MikuroXina requested changes

2023-11-06 09:23 UTC, MikuroXina commented on pkg/accounts/model/account.ts
> +  }
現在の状態からそこへ遷移してもよいのかどうか, 検査しないのでしょうか? それともサイレンス中に凍結を行った場合には, その凍結を解除してもサイレンス状態が維持されるのでしょうか? この辺りのステートマシンは別の型として掃き出してよさそうです

2023-11-06 09:23 UTC, MikuroXina commented on pkg/accounts/model/account.ts
> +  }
現在の状態から遷移すべきではないものはありませんか? それともサイレンス中に凍結を行った場合には, その凍結を解除してもサイレンス状態が維持されるのでしょうか?

2023-11-06 09:34 UTC, laminne commented on pkg/accounts/model/account.ts
> +  }
```mermaid
stateDiagram-v2
	NOT_ACTIVATED --> ACTIVE
	ACTIVE --> FROZEN
	ACTIVE --> SILENCED
	SILENCED --> FROZEN
	FROZEN --> SILENCED
	SILENCED --> ACTIVE
	FROZEN --> ACTIVE
```
こんな感じの想定をしていました
(サイレンス中に凍結を行い、それを解除するとサイレンスに戻る)

2023-11-06 11:55 UTC, m1sk9 submitted a review, later dismissed

2023-11-07 12:38 UTC, MikuroXina reviewed
削除済みかどうかの判定を行っていませんが, 削除済みのアカウントに対するあらゆる操作は抑制されるべきでしょうか?

2023-11-07 13:50 UTC, m1sk9 commented
> 削除済みかどうかの判定を行っていませんが, 削除済みのアカウントに対するあらゆる操作は抑制されるべきでしょうか?

されるべきだと思う.

2023-11-08 01:01 UTC, MikuroXina submitted a review, later dismissed

2023-11-08 01:34 UTC, m1sk9 submitted a review, later dismissed

2023-11-08 03:14 UTC, m1sk9 approved these changes

2023-11-08 03:14 UTC, merged