feat: implements EtagService
approvers/pulsate pull request #90
Opened 2023-11-16 22:43 UTC by aqyuki

## What does this PR do?

This PR add a EtagService.

1. `EtagService` provide two methods, `compare` and `generate`

    - `compare` compares the Etag of the account with the given account name with the Etag passed and returns the result.
    - `generate` generate a Etag from given account.

2. Update import map

2023-11-16 22:55 UTC, laminne requested changes
ETagServiceだと何するサービスなのかが分かりにくいので命名を見直してください

2023-11-17 01:16 UTC, aqyuki commented
Service名を`EtagService`から`EtagGenerateSercvice`に変更しました。
それに伴って`compare`メソッドを`EtagGenerateService`のクラスから削除しました。

2023-11-17 01:34 UTC, laminne requested changes
Compareは必要だと思います(生成だけにすると責務が微妙なところで分割されてしまうので)  
Etagがなんのために使われるのかがわかるような命名にしてほしいです

2023-11-17 01:35 UTC, aqyuki commented
EtagVertifyとかですかね？

2023-11-17 01:43 UTC, m1sk9 commented on pkg/accounts/service/etag_generate_service.test.ts
(To other reviewer)

他のテストコードと同様に `InMemoryAccountRepository` を使いメモリーにアカウントを登録する形でテスト終了後に `clear` method でアカウントを削除すると言う一連の形で共通化したいと考えていますが, どうですか.

2023-11-17 01:54 UTC, laminne commented
クラス名は`EtagGenerateService`で良いと思いますが、TSDocなどでETagがどのように使われるか(ニックネームを更新したときの検証などに使われる)を書いておくべきと思います

2023-11-17 01:55 UTC, laminne commented on pkg/accounts/service/etag_generate_service.test.ts
そうしたほうが良いと思います.(後でドキュメントに書く必要がありますね)

2023-11-17 02:06 UTC, aqyuki commented on pkg/accounts/service/etag_generate_service.test.ts
このサービスでは、Etagの生成時にアカウントの情報が必要なだけでわざわざクラス内に`AccountRepository`をもつ必要は無いのと思うのですがどうですかね？

2023-11-17 02:53 UTC, m1sk9 commented on pkg/accounts/service/etag_generate_service.test.ts
じゃあその方向でいきましょう

2023-11-17 02:55 UTC, m1sk9 requested changes

2023-11-17 02:55 UTC, m1sk9 commented on pkg/accounts/service/etag_generate_verift_service.test.ts
MUST:

InMemoryAccountRepository を使いメモリーにアカウントを登録する形でテスト終了後に `clear` method でアカウントを削除してください.

2023-11-17 03:10 UTC, aqyuki commented on pkg/accounts/service/etag_generate_verift_service.test.ts
`clear`メソッドが `InMemoryAccountRepository` に無いのですが`reset`メソッドを使ってアカウントを消すってイメージでいいですか？

2023-11-17 03:15 UTC, m1sk9 commented on pkg/accounts/service/etag_generate_verift_service.test.ts
それが正しい本来のメソッドですね.

2023-11-17 03:16 UTC, aqyuki commented on pkg/accounts/service/etag_generate_verift_service.test.ts
わかりました

2023-11-18 07:44 UTC, m1sk9 commented
Notes:
ちょっと怪しいところがちょこちょこあるので, @laminne , @m1sk9 両者のレビューを待ってください.

2023-11-18 08:04 UTC, m1sk9 requested changes

2023-11-18 08:10 UTC, m1sk9 requested changes
追加です.

2023-11-18 08:10 UTC, m1sk9 commented on pkg/accounts/service/etag_generate_verift_service.test.ts
> +  assertEquals(Result.isErr(res), false);
アカウント作成の検証は [`Result.unwrap()`](https://mikuroxina.github.io/mini-fn/functions/Result.unwrap.html) を使ってください.

2023-11-18 08:10 UTC, laminne requested changes

2023-11-18 08:10 UTC, laminne commented on pkg/accounts/service/etag_verify_generate_service.ts
> +  async compare(account: Account, etag: string): Promise<boolean> {
[may]
`compare`だと文章的におかしい気がします. `verify`といった命名のほうがわかりやすいかと.
```suggestion
  async verify(account: Account, etag: string): Promise<boolean> {
```

2023-11-18 08:10 UTC, laminne commented on pkg/accounts/service/etag_verify_generate_service.ts
> +   * Generate Etag from given account.
[should]
生成する`ETag`の仕様を書いたほうが良い気がします(ただ、英訳するのにコストが掛かるのでやらなくてもいいとは思いますが…

2023-11-18 08:19 UTC, m1sk9 commented on pkg/accounts/service/etag_verify_generate_service.ts
> +export class EtagVerifyService {
> [SHOULD]
> ETagがどういうものなのかを何処かのドキュメントを(URLを貼る形で)参照するべきだと思います.

MDN がドキュメントを公開していたので教えておきます. これよりわかりやすいドキュメントを知っているのであればそれでも構いません. ( MDN より信用できる情報源が気軽に公開されているかどうかは不明ですが. )
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

2023-11-18 10:09 UTC, laminne approved these changes

2023-11-18 11:53 UTC, m1sk9 approved these changes
LGTM

2023-11-18 11:53 UTC, merged